### ISSUE TITLE
mate 9 do you want but it?

### ISSUE THREAD

**Issue by FYH-fly** [1187981465/Note#3]
the price 
| HUAWEI  Mate 9 全网通 4GB 32GB     | 【内部处理机】HUAWEI  Mate9 全网通版 4GB+32GB（苍穹灰）  | 162  |
| ------------------------------- | ---------------------------------------- | ---- |
| HUAWEI Mate 9  全网通 4GB 32GB     | 【内部处理机】HUAWEI Mate9  全网通版 4GB+32GB（月光银）  | 397  |
| HUAWEI Mate 9  全网通 4GB 64GB 高配版 | 【内部处理机】HUAWEI Mate9  全网通版 4GB+64GB（香槟金）  | 117  |
| HUAWEI Mate 9  全网通 4GB 64GB 高配版 | 【内部处理机】HUAWEI Mate9  全网通版 4GB+64GB （摩卡金） | 216  |
| HUAWEI Mate 9  全网通 4GB 64GB 高配版 | 【内部处理机】HUAWEI Mate9  全网通高配版 4GB+64GB（陶瓷白） | 60   |
| HUAWEI Mate 9  全网通 4GB 64GB 高配版 | 【内部处理机】HUAWEI Mate9  全网通高配版 4GB+64GB（黑色） | 297  |

**Comment by rqhua** [comment]
it's so expensive for me ...

**Comment by FYH-fly** [comment]
the price 32GB ￥2400，64GB ￥2800. if you need it ， call me later.
